### ISSUE TITLE
Report needs to be version 1.1.0

### ISSUE THREAD

**Issue by rlorenzo** [h5p/h5p-php-report#10]
See the comment here: https://h5p.org/comment/29526#comment-29526

We get the same error that people reported in there in our Moodle: Version 1.1.0 of the reporting module is required to render this report. Currently installed: 1.0.0

We had to manually change the version number here: https://github.com/h5p/h5p-php-report/blob/master/h5p-report.class.php#L9

To fix this for others, can you please update this version so the https://github.com/h5p/moodle-mod_hvp repo can update it's submodule?

**Comment by thomasmars** [comment]
There's a pull request for this at https://github.com/h5p/h5p-php-report/pull/7
