### ISSUE TITLE
h5p-report.class.php looking for minimum 1.1.0

### ISSUE THREAD

**Issue by dustinbrisebois** [h5p/h5p-php-report#6]
We are seeing reports of H5P requesting report version of 1.1.0 minimum however the available version is 1.0 -- as per: https://h5p.org/node/577412

Can we have the h5p-php-report updated to 1.1, patched to 1.1 OR the requirement rolled back until it is?

h5p-report.class.php as follows on line 10
`  private static $version = '1.1.0';
`

**Comment by thomasmars** [comment]
See https://github.com/h5p/h5p-moodle-plugin/issues/302
