### ISSUE TITLE
Fill in the blanks report doesn't work in Moodle

### ISSUE THREAD

**Issue by jarvil1** [h5p/h5p-php-report#9]
This "Version 1.1.0 of the reporting module is required to render this report. Currently installed: 1.0.0"  problem persists in 

- mod_hvp 1.21.0
- Fill in the Blanks (1.12.5)
- Moodle 3.5

https://github.com/h5p/h5p-blanks/issues/48

the difference is that now when student has answered and you click report you get an error "Version 1.1.0 of the reporting module is required to render this report. Currently installed: 1.0.0"

![helsinkin](https://user-images.githubusercontent.com/53904029/91154155-d5eb3d00-e6c9-11ea-85a3-4cdaef6f8407.PNG)

**Comment by thomasmars** [comment]
There's a pull request for this already, please follow the issue there https://github.com/h5p/h5p-php-report/pull/7
